name: CI

# Other types of triggers exist -- lookup the docs to see! on new git pushes is most useful
# on:
#  milestone:
#    type: [closed]

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CocoaPod Install
        run: pod install
      #- name: Use this line to see how many versions of Xcode are installed on the CI
      #  run: ls /Applications | grep Xcode

      # Use this if your app requires a specific Xcode (or breaks on the latest one haha)
      #- name: Force xcode 11 
      #  run: sudo xcode-select -switch /Applications/Xcode_11.4.app
      # - how to run build/test all in one line for starters
#      - name: iPhone 11 Test
#        run:  xcodebuild test -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
      
#      - name: iPad Air Test
#        run:  xcodebuild test -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.1'
      - name: iOS build setup
        run: |
          xcodebuild build-for-testing -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12' #-allowProvisioningUpdates
      
      - name: testing ... iPhone 12
        run: xcodebuild test-without-building -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12'
        
      - name: testing ... iPhone 12 Pro Max
        run: xcodebuild test-without-building -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max'

      - name: testing ... iPad Air
        run: xcodebuild test-without-building -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPad Air (3rd generation)'
      
#      - name: testing ... iPad Pro 12.9
#        run: xcodebuild test-without-building -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (3rd generation)'

#    http://patorjk.com/software/taag/#p=display&f=3D%20Diagonal&t=Affirm%20Me%20iOS
#          echo "Welcome to\                
#             _         ___    ___  _                         ____    ____          _    ___     ______  \
#            / \      .' ..] .' ..](_)                       |_   \  /   _|        (_) .'   `. .' ____ \ \
#           / _ \    _| |_  _| |_  __   _ .--.  _ .--..--.     |   \/   |  .---.   __ /  .-.  \| (___ \_|\
#          / ___ \  '-| |-''-| |-'[  | [ `/'`\][ `.-. .-. |    | |\  /| | / /__\\ [  || |   | | _.____`. \
#        _/ /   \ \_  | |    | |   | |  | |     | | | | | |   _| |_\/_| |_| \__.,  | |\  `-'  /| \____) |\
#       |____| |____|[___]  [___] [___][___]   [___||__||__] |_____||_____|'.__.' [___]`.___.'  \______.'"
      
# Available simulators in Xcode 11.1
#    { platform:iOS Simulator, id:D032379D-635D-4781-B596-623CB9CBF745, OS:13.1, name:iPad Air (3rd generation) }
#		{ platform:iOS Simulator, id:B55B52B5-6677-4771-9488-7916C5B17C59, OS:13.1, name:iPad Pro (9.7-inch) }
#		{ platform:iOS Simulator, id:6516ECC0-7CE5-4AA6-8F04-816506455380, OS:13.1, name:iPad Pro (11-inch) }
#		{ platform:iOS Simulator, id:287E0905-1417-4C70-987E-3F1B70544468, OS:13.1, name:iPad Pro (12.9-inch) (3rd generation) }
#		{ platform:iOS Simulator, id:6A7CFA76-FE25-4A9E-818E-4E1435415233, OS:13.1, name:iPhone 8 }
#		{ platform:iOS Simulator, id:4C38A616-8069-402C-8580-EFF323001A42, OS:13.1, name:iPhone 8 Plus }
#		{ platform:iOS Simulator, id:C45229CE-8038-4FE5-AA75-46E2080ED9C3, OS:13.1, name:iPhone 11 }
#		{ platform:iOS Simulator, id:6848AD49-7FE1-41CA-93AE-2F96474F6BB3, OS:13.1, name:iPhone 11 Pro }
#		{ platform:iOS Simulator, id:ED8673D7-F76C-4BCB-8FAE-01795C43FB39, OS:13.1, name:iPhone 11 Pro Max }

